### ISSUE TITLE
Ehancement: wl-summary-pick-threads

### ISSUE THREAD

**Issue by jeeger** [wanderlust/wanderlust#110]
I wrote a little helper function that does a search, and fully marks all the threads containing a marked message. This is useful for refiling, as it doesn't leave old messages without a thread lying around. Maybe this could be integrated into wanderlust proper? (Prefix argument for wl-summary-pick, maybe?

Code:

```emacs-lisp
(defun wl-summary-pick-threads (&optional from-list delete-marks)
  (interactive "i\nP")
  (wl-summary-pick from-list delete-marks)
  (save-excursion
    (goto-char (point-min))
    (lexical-let ((saved-target-mark-list wl-summary-buffer-target-mark-list))
      (cl-loop
       for number in saved-target-mark-list
       do
       (wl-summary-jump-to-msg number)
       (wl-summary-target-mark-thread)))))
```

**Comment by ikazuhiro** [comment]
Prefix argument for `wl-summary-pick` is already used to remove existing marks before search.  How about a new function to pick threads from existing marks?  Please try `m` `T` after search.

```lisp
(eval-after-load "wl-summary"
  '(progn
     (define-key wl-summary-mode-map "mT"   'wl-summary-target-mark-threads)

     (defun wl-summary-target-mark-threads ()
       (interactive)
       (if wl-summary-buffer-target-mark-list
           (save-excursion
             (let ((mark-list wl-summary-buffer-target-mark-list))
               (dolist (number mark-list)
                 (wl-summary-jump-to-msg number)
                 (wl-summary-target-mark-thread))))
         (wl-summary-target-mark-thread)))))
```

**Comment by jeeger** [comment]
Yes, a great idea. That should work. 

Am 24. Dezember 2015 10:02:09 MEZ, schrieb Kazuhiro Ito <notifications@github.com>:
>Prefix argument for `wl-summary-pick` is already used to remove
>existing marks before search.  How about a new function to pick threads
>from existing marks?  Please try `m` `T` after search.
>
>```lisp
>(eval-after-load "wl-summary"
>  '(progn
>(define-key wl-summary-mode-map "mT"   'wl-summary-target-mark-threads)
>
>     (defun wl-summary-target-mark-threads ()
>       (interactive)
>       (if wl-summary-buffer-target-mark-list
>           (save-excursion
>             (let ((mark-list wl-summary-buffer-target-mark-list))
>               (dolist (number mark-list)
>                 (wl-summary-jump-to-msg number)
>                 (wl-summary-target-mark-thread))))
>         (wl-summary-target-mark-thread)))))
>```
>
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/wanderlust/wanderlust/issues/110#issuecomment-167072223

-- 
Diese Nachricht wurde von meinem Mobiltelefon gesendet.

**Comment by ikazuhiro** [comment]
Commited at https://github.com/wanderlust/wanderlust/commit/69edbd8b0c306a19237003a03c1da2cc567a119e .
