### ISSUE TITLE
Incorrect threading in wanderlust.info

### ISSUE THREAD

**Issue by jech** [wanderlust/wanderlust#111]
There are some threading problems in the English-language info file -- the two children of the Quick Sort node don't have any up/next/previous pointers.

**Comment by ikazuhiro** [comment]
Should be fixed at https://github.com/wanderlust/wanderlust/commit/5dba92992d54ae5403b19b7143ab3f7770cacec8.  Names of Quick Search's child nodes are changed because they are too common.
