### ISSUE TITLE
Correct address rejected

### ISSUE THREAD

**Issue by jech** [wanderlust/wanderlust#115]
When hitting reply, I got a header like this:

    To: foo@example.com <foo@example.com>

This was rejected by Wanderlust with `Error while parsing address`.

**Comment by egh** [comment]
This email address is not correct, at least according to http://emailregex.com/

**Comment by jech** [comment]
Right.  RFC 5322, Section 3.2.3.

I still find it confusing that when I hit reply, WL inserts an address that it later rejects, but I guess I should close this ticket.
