### ISSUE TITLE
Seems invalid function call when exiting wl

### ISSUE THREAD

**Issue by 8ring** [wanderlust/wanderlust#116]
Upon exit, after confirmation, an error occurs, as follows.

> bbdb-wl-exit: Symbol's function definition is void: bbdb-offer-save

It is in file `bbdb-wl.el`. I think `bbdb-offer-save` is a variable, not a function. It gets used in the following places in that file:

```
(defun bbdb-wl-setup ()
  ...
  (add-hook 'wl-save-hook 'bbdb-offer-save)
  ... )
```
and
```
(defun bbdb-wl-exit ()
  ...
  (bbdb-offer-save))
```

**Comment by ikazuhiro** [comment]
The bundled `bbdb-wl.el` is not maintained and does not work with BBDB 3.x.  Please see [the documentation](http://wanderlust.github.io/wl-docs/wl.html#BBDB) and [the related discussion](http://thread.gmane.org/gmane.mail.wanderlust.general.japanese/9994).

**Comment by 8ring** [comment]
Thanks. My fault that I didn't check there.
