### ISSUE TITLE
Offline queue not saved when killing Emacs

### ISSUE THREAD

**Issue by jech** [wanderlust/wanderlust#117]
This is a second-hand report from  http://emacs.stackexchange.com/questions/21819/wanderlust-save-restore-queued-operations-accross-sessions .

Lawlist reports that the offline queue is not saved when killing Emacs without calling `wl-exit`.  The issue is that the `kill-emacs-hook` only calls `wl-save-state`, not `elmo-quit`.

**Comment by ikazuhiro** [comment]
Shoud be fixed at https://github.com/wanderlust/wanderlust/commit/3e29a10cddbae350aea5aefd69ba1cded5071a35 .

**Comment by ikazuhiro** [comment]
Closing.  If you still has problems, please report.
