### ISSUE TITLE
POP (Gmail) troubles

### ISSUE THREAD

**Issue by zaezsh** [wanderlust/wanderlust#118]
folders:

&user@pop.gmail.com:995!   "+ "
+inbox    "Входящие  "
+trash     "Корзина  "    
+draft      "Черновики  "
|&user@pop.gmail.com|+inbox  ">  "

Without adding pipe folder incoming mail are completely destroyed: it doesn't exist on the server, and it doesn't remain in the folder "&user9@pop.gmail.com:995!". But after adding:
|&user9@pop.gmail.com|+inbox  ">"
new messages don't move to +inbox and wanderlust (Emacs) hangs up on "cheking |&user9@pop.gmail.com|+inbox  >"

You don't have this instruction for POP3 folders, and for me it is unacceptable to lose messages.
And I don't use IMAP from security reasons in case of an account compromise :)

It is possible to see an example of a working config for POP3 Gmail with saving incoming messages?

**Comment by ikazuhiro** [comment]
As fas as I tested, Gmail's POP3 server is very unique, which makes a message invisible once you have downloaded (fetched) it.
I think you should use [recent mode](https://support.google.com/mail/answer/47948) to view Gmail's POP3 folder, which show only the last 30 days of messages but you can download them any number of times.
For example, if your account is `example@gmail.com`, recent mode folder is `&"recent:example@gmail.com"@pop.gmail.com:995!`
Pipe folder also doesn't work with Gmail's recent mode on my environment, but I don't have much time to investigate.

**Comment by zaezsh** [comment]
If pipe folder doesn't work, how to save inbox mail on Gmail in MH mailbox? Reading a manual doesn't answer the matter.
Support of PO3 is temporarily stopped?

**Comment by ikazuhiro** [comment]
>> Gmail's POP3 server is very unique, which makes a message invisible once you have downloaded (fetched) it.

> Really messages, received according to the POP protocol aren't deleted from server?

I think the result depends on Gmail's settings. Please see [Google's document](https://support.google.com/a/answer/6089246).

> If pipe folder doesn't work, how to save inbox mail on Gmail in MH mailbox?

After entering Gmail's POP3 folder, you can refile messages manually by `o` (wl-summary-refile) or `r o` (wl-summary-refile-region) at Summary buffer.

**Comment by ikazuhiro** [comment]
Pipe folder with Gmail's POP3 folder (regardless recent mode or not) works for me.  I simply had written wrong folder spec.
Both `|&"recent:example@gmail.com"@pop.gmail.com:995!|+inbox` and `|&"example@gmail.com"@pop.gmail.com:995!|+inbox` work fine.

I tested with Gamil's setting "2. When messages are accessed with POP" in "POP Download"
to "keep Gmail's copy in the Inbox".

**Comment by zaezsh** [comment]
I recreated a configuration (with "`recent:example@gmail.com`") and now it works too. But! Without option "Leave Message on the Server: y/n" all this not that shall be. (At same time in settings of Gmail option "Delete message after POP download" is active, but Wanderlust doesn't delete messages).

**Comment by zaezsh** [comment]
All works! This issue may be closed.
