### ISSUE TITLE
`wl-draft-use-frame' ignored in WL's `compose-mail' interface

### ISSUE THREAD

**Issue by dmj** [wanderlust/wanderlust#120]
`wl-user-agent-compose' dynamically binds`wl-draf-use-frame' _only_ based on the value of `switch-function'.

Originally reported by Pascal Haakmat on the WL mailing list.

**Comment by ikazuhiro** [comment]
It is intended.  `wl-user-agent-compose` obeys compose-mail's rule. You should use `compose-mail-other-frame` function instead of `compose-mail` or `compose-mail-other-window`.
