### ISSUE TITLE
Cannot reply to PGP-encrypted mail

### ISSUE THREAD

**Issue by jech** [wanderlust/wanderlust#124]
I receive a PGP encrypted mail.  I press `v` on the MIME part, choose `read the message, then press `a`.  I get the error

    wl-draft-reply: No match field: check your ‘wl-draft-reply-without-argument-list’

**Comment by ikazuhiro** [comment]
Please use `C-c  C-t C-c` instead of `v`.  Decrypted message is displayed as inline and you can normally reply it.

**Comment by jech** [comment]
Ah, right.  Thanks.
