### ISSUE TITLE
k S and k N too easy to hit in Summary mode

### ISSUE THREAD

**Issue by jech** [wanderlust/wanderlust#125]
I find myself often typing `k S` and `k N` by mistake in the _Summary_ buffer when I meant to type `k n` or `k s`.  Of course, this pollutes my bayesian database.

I suggest that, by default, `k S` and `k N` should ask for confirmation before performing the action.

**Comment by ikazuhiro** [comment]
Done at f7bb1a662893b5aacd3f358f927c05ee47d08a5e.  Now `k S` and `k N` confirm before execution.  BTW, I recommend you to use `k m` instead of `k s`
