### ISSUE TITLE
Encoded commas in e-mail addresses

### ISSUE THREAD

**Issue by jech** [wanderlust/wanderlust#126]
I just received an e-mail from

```
=?utf-8?B?QmFvemh1LCBadW8=?= <baozhu.zuo@example.com>
```

this decodes to

```
Baozhu, Zuo <baozhu.zuo@example.com>
```

which, due to the comma, makes for an incorrect header when hitting Reply.  I don't see a good solution to this problem.

**Comment by ikazuhiro** [comment]
Please try [the patch](https://gist.github.com/ikazuhiro/8f89f4ea07100404a48b34423516807f) to FLIM.
I'll commit it into the repository after more test, because it changes very essential function of decoder.

**Comment by ikazuhiro** [comment]
I push [the fix](https://github.com/wanderlust/flim/commit/575bfbf09b9d129c9b25776950be71594b375ea3).  Please test.

**Comment by jech** [comment]
Sorry, Kazuhiro-san, but I won't be able to do so before September.

**Comment by ikazuhiro** [comment]
Closing.  Please create new issue if you still have the problem.
