### ISSUE TITLE
Wanderlust will not start up with emacs 25 and certain configuration

### ISSUE THREAD

**Issue by egh** [wanderlust/wanderlust#127]
Since a recent upgrade, either of emacs or wanderlust, Wanderlust seems to lock on start with emacs 25. I am on Wanderlust version 20160728.756 from MELPA and emacs:

GNU Emacs 24.5.1 (x86_64-pc-linux-gnu, GTK+ Version 3.18.9) of 2016-04-17 on lgw01-04, modified by Debian

installed via the emacs PPA (https://launchpad.net/~ubuntu-elisp/+archive/ubuntu/ppa) version. The package version is: 2:201608030101~ubuntu16.04.1

This is on Ubuntu 16.04.

Here is a minimal example which shows the problem for me:
```elisp
(setq elmo-maildir-folder-path "~/maildir"
      wl-draft-folder ".drafts"
      wl-trash-folder ".trash"
      wl-queue-folder ".queue"
      elmo-lost+found-folder ".lost+found"
      package-archives '(("melpa" . "https://melpa.org/packages/")))

(package-initialize)
(package-refresh-contents)
(package-install 'wanderlust)
(wl)
```

Note that my maildir is in `~/maildir`. I have about 30k messages there.

Note that I cannot reproduce this issue on emacs 24.

**Comment by egh** [comment]
I cannot reproduce on wanderlust-20160704.313 on GNU Emacs 25.1.50.2 (x86_64-pc-linux-gnu, GTK+ Version 3.18.9) of 2016-08-04 (emacs ppa version 2:201608050101~ubuntu16.04.1)

**Comment by egh** [comment]
Cannot reproduce on Wanderlust 20160728.756 on GNU Emacs 25.1.50.2 (x86_64-pc-linux-gnu, GTK+ Version 3.18.9) of 2016-08-04 (emacs ppa version 2:201608050101~ubuntu16.04.1).

I assume that something has been fixed in the latest version of emacs. I'll check the other computer tomorrow.

**Comment by egh** [comment]
Please ignore my last 2 updates: these were on a machine that had no mail in `~/maildir`

**Comment by egh** [comment]
After building emacs from source and running via gdb, starting `M-x wl` and then interrupting when it locks up gets me:
```
(gdb) run -nw
Starting program: /home/egh/c/emacs/src/emacs -nw
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff0c5e700 (LWP 9877)]

Thread 1 "emacs" received signal SIGTSTP, Stopped (user).
0x00007ffff507d757 in kill () at ../sysdeps/unix/syscall-template.S:84
84	../sysdeps/unix/syscall-template.S: No such file or directory.
(gdb) xbacktrace
"elmo-location-map-load" (0xffffb2b0)
0x4519580 PVEC_COMPILED
"apply" (0xffffb5e0)
"luna-call-next-method" (0xffffb7e0)
"luna-apply-generic" (0xffffb9e0)
"elmo-folder-open-internal" (0xffffbbf0)
"wl-draft-queue-flush" (0xffffbe20)
"wl-toggle-plugged" (0xffffc020)
"wl-plugged-init" (0xffffc220)
"wl" (0xffffc4e0)
"funcall-interactively" (0xffffc4d8)
0xb2b4b0 PVEC_SUBR
"ad-Advice-call-interactively" (0xffffc918)
"apply" (0xffffca88)
"call-interactively" (0xffffcc50)
"command-execute" (0xffffce28)
"execute-extended-command" (0xffffd010)
"smex-read-and-run" (0xffffd1c0)
"smex" (0xffffd540)
"funcall-interactively" (0xffffd538)
0xb2b4b0 PVEC_SUBR
"ad-Advice-call-interactively" (0xffffd848)
"apply" (0xffffd9b8)
"call-interactively" (0xffffdb80)
"command-execute" (0xffffdd28)
(gdb) 
```

**Comment by egh** [comment]
Deleting `.elmo` seems to fix the issue. I assume something changed in a recent version of emacs that broke this.

**Comment by ikazuhiro** [comment]
Between these version of Wanderlust `location` file format is changed.
This file is also used for maildir folder.  So, this change may affect
the result.  But if your Emacs crashes or hangs, I think it is Emacs's
problem.

**Comment by egh** [comment]
Thanks for your response. I'll close this ticket and hope that if anybody else has the issue they will see it.
