### ISSUE TITLE
recent change in emacs-master breaks wanderlust

### ISSUE THREAD

**Issue by Dickby** [wanderlust/wanderlust#132]
Recently some default variables have been removed:

http://git.savannah.gnu.org/cgit/emacs.git/commit/?id=73d47d22197175f08b2dd62e76d7138872e611d2

one of the removed variables is `default-truncate-lines`
this breaks wl.

**Comment by ikazuhiro** [comment]
I've committed the fix.  Please confirm.

**Comment by Dickby** [comment]
It works again.
Thanks!
