### ISSUE TITLE
in summary view of folder seems don't find data of messages

### ISSUE THREAD

**Issue by jldomenech** [wanderlust/wanderlust#135]
All the messages retrieved with the last version of wanderlust found in melpa shows as:

  N ?? 00-00-0 [ nobody@nowhere? ] (WL:No Subject in original.)

in summary mode but the mime view shows the message correctly.

**Comment by ikazuhiro** [comment]
Sorry, I've commit the fix for the case that  `elmo-msgdb-extra-fields` is `nil`.  Please retry with the latest.

**Comment by jldomenech** [comment]
Sorry, I using dda6c57fa58ef19cfd1be199a791a3e35096b5cf I still get the same results.

**Comment by hskuhra** [comment]
The fix works for me! Thanks.

**Comment by jldomenech** [comment]
It works for me (from melpa). Sorry for the inconvenience, perhaps the problem was with my installation from git.
Yes, I was rebuilding summary.

**Comment by ikazuhiro** [comment]
I'm closing the issue.
