### ISSUE TITLE
Does someone have a copy of spamfilter.el?

### ISSUE THREAD

**Issue by tarsius** [wanderlust/wanderlust#138]
I would like to add `spamfilter` to the Emacsmirror (because I try to add all dependencies of all packages that are already mirrored).

Unfortunately I cannot find that library anywhere. Since this package uses it, I am hoping that someone who reads this can point me to the upstream or else could send me a copy.

Thanks!

**Comment by AlexanderS** [comment]
Something like this: http://www.geocities.co.jp/SiliconValley-PaloAlto/7043/spamfilter/spamfilter.el.txt

(Link is from this emacswiki page: https://www.emacswiki.org/emacs/?CategoryMailAddons)

**Comment by tarsius** [comment]
So now I have to figure out where to get `chasen` and `japanese-tokenizer`. I think I'm gonna give up on this particular rabbit hole and just live with `spamfilter` being missing.

But thanks for the link.

I'll leave this open in case the Wanderlust maintainers might want to do something about these hard to acquire dependencies.

**Comment by AlexanderS** [comment]
Just tried the simple way:

- http://www.geocities.co.jp/SiliconValley-PaloAlto/7043/spamfilter/chasen.el.txt
- http://www.geocities.co.jp/SiliconValley-PaloAlto/7043/spamfilter/japanese-tokenizer.el.txt

**Comment by tarsius** [comment]
Thanks! I guess I'll add them anyway, now that you have done the work ;-)

But I wonder: are these libraries still functioning properly, after all they haven't been touched in over a decade! Is anyone here actually using these libraries?
