### ISSUE TITLE
Recent bbdb versions do not provide bbdb-hooks

### ISSUE THREAD

**Issue by tarsius** [wanderlust/wanderlust#139]
At the end of `bbdb-wl.el` an attempt is made to load `bbdb-hooks`, provided `bbdb-wl-extract-field-value-internal` is not bound as a function. In recent `bbdb` version that function doesn't exist and so loading `bbdb-wl.el` will fail.

Thanks for looking into this.

**Comment by ikazuhiro** [comment]
`utils/bbdb-wl.el` is for old bbdb package and is not compatible with bbdbv3.  Because [latest bbdb supports Wanderlust by itself](http://git.savannah.gnu.org/cgit/bbdb.git/commit/?id=7a43a481b8c42f08fa10aa140cf2884f8e36040c), I think there is no need for additional work.

**Comment by tarsius** [comment]
Thanks for the information!

Are there any other libraries that are only kept to support older versions of third-party packages, or fur other compatibility reasons?

**Comment by ikazuhiro** [comment]
Actually, `utils/bbdb-wl.el` simply remains unmaintained for a long time.  Because I don't know state of external packages and programs on which Wanderlust depends (especially which I don't use), I neither know whether current code works with current external packages correctly.

**Comment by tarsius** [comment]
Okay that addresses the issue for me for the time being. Thanks for your time.
