### ISSUE TITLE
mu -- searching with multiple arguments.

### ISSUE THREAD

**Issue by lawlist** [wanderlust/wanderlust#141]
Example #1:  `[date:2010..2011 flag:signed emacs]!mu`

Example #2:  `[flag:unread maildir:/INBOX]!mu`

As far as I can determine, there is no built-in support to handle multiple arguments when searching.  The pattern (everything inside the square brackets) is passed as one string.

Here is one method of supporting multiple arguments separated by a `|`

Example #1 -- *revised*:  `[date:2010..2011|flag:signed|emacs]!mu`

Example #2 -- *revised*:  `[flag:unread|maildir:/INBOX]!mu`

    (luna-define-method elmo-search-engine-do-search ((engine elmo-search-engine-extprog) pattern)
      (with-temp-buffer
        (let* (
            (charset (elmo-search-engine-extprog-charset-internal engine))
            (parser (or (elmo-search-engine-extprog-parser-internal engine)
                        #'elmo-search-parse-filename-list))
            (program-arguments
              (delq nil
                (elmo-flatten
                  (mapcar
                    (lambda (arg)
                      (cond
                        ((stringp arg)
                          arg)
                        ((eq arg 'pattern)
                          ;;; `elmo-search-engine-do-search' has been modified so that
                          ;;; `pattern` may be multiple arguments separated by |
                          ;;; EXAMPLE:  ["flag:unread|maildir:/INBOX"]!mu
                          (let ((arguments
                                  (if charset
                                    (encode-mime-charset-string pattern charset)
                                    pattern)))
                            (if (string-match "|" arguments)
                              (split-string arguments "|")
                              arguments)))
                        ((functionp arg)
                          (condition-case nil
                            (funcall arg engine pattern)
                            (wrong-number-of-arguments (funcall arg engine))))
                        ((and (symbolp arg) (boundp arg))
                          (symbol-value arg))))
                    (elmo-search-engine-extprog-args-internal engine))))))
          ;;; DEBUGGING
          ;; (message "program-arguments: %s" program-arguments)
          (apply 'call-process
           (elmo-search-engine-extprog-prog-internal engine) nil t t program-arguments)
          (funcall parser))))

**Comment by egh** [comment]
Wanderlust should use `elmo-search-split-pattern-list` to split the patterns by spaces.

**Comment by lawlist** [comment]
@egh -- Ah . . . The version of elmo/wanderlust that I have been using is from a few years ago, and it appears the `elmo-search-split-pattern-list` was invented sometime within that time-span.  Next time I'll try out a current version of everything before posting an issue.  Thank you for teaching me about this new function -- greatly appreciated.

**Comment by egh** [comment]
My pleasure! To be honest it doesn't seem to match exactly the results I get from the command line, which is a little strange, so it might not be working entirely correctly.
