### ISSUE TITLE
wl-folder-sync-entity:  modify to permit all flag updates to local database

### ISSUE THREAD

**Issue by lawlist** [wanderlust/wanderlust#142]
`wl-folder-sync-entity` does not update the IMAP local flag database with things like `'forwarded`.  After running `wl-folder-sync-entity` (ON-line), and then going to a folder with `wl-folder-jump-to-current-entity` (OFF-line), the flags will not be updated with `'forwarded` flags until the next time on-line synchronization occurs through the summary buffer.  The following suggested approach makes it so that `wl-summary-sync-marks` can be used without having a summary buffer open, and I put that into `wl-folder-sync-entity`.

    (defun wl-folder-sync-entity (entity &optional unread-only)
    "Synchronize the msgdb of ENTITY."
      (cond
        ((consp entity)
          (let ((flist (nth 2 entity)))
            (while flist
              (wl-folder-sync-entity (car flist) unread-only)
              (setq flist (cdr flist)))))
        ((stringp entity)
          (let* (
              (folder (wl-folder-get-elmo-folder entity))
              (nums (wl-folder-get-entity-info entity))
              (new (or (car nums) 0))
              (unread (or (cadr nums) 0)) )
            (when (or
                    (not unread-only)
                    (or (> new 0) (> unread 0)))
              (let ((summary (wl-summary-get-buffer entity))
                     (range (wl-summary-get-sync-range folder)))
                (if summary
                    (save-selected-window
                      (with-current-buffer summary
                        (let ((win (get-buffer-window summary t)))
                          (when win
                            (select-window win)))
                        (wl-summary-sync 'unset-cursor range)
                        (wl-summary-save-status)))
                  (elmo-folder-open folder 'load-msgdb)
                  (unwind-protect
                    (progn
                      (elmo-folder-synchronize folder nil (eq range 'all))
                      (wl-summary-sync-marks folder) ;; needed to update the `flag` file with `forwarded`
                      (wl-folder-set-folder-updated
                       entity
                       (list
                        0
                        (or (cdr (assq 'unread (elmo-folder-count-flags folder)))
                      0)
                        (elmo-folder-length folder))))
                        (elmo-folder-close folder)))))))))
    
    (defun wl-summary-sync-marks (&optional folder)
    "Update persistent marks in summary."
    (interactive)
      (let* ((folder (or folder wl-summary-buffer-elmo-folder))
             (mes "Updated ")
             (folder-name (elmo-folder-name-internal folder))
             diff diffs)
        (message "wl-summary-sync-marks:  Updating persistent marks (%s) ..." folder-name)
        (dolist (flag (wl-summary-get-available-flags))
          (setq diff
                  (elmo-list-diff
                    (elmo-folder-list-flagged folder flag)
                    (elmo-folder-list-flagged folder flag 'in-msgdb)))
          (setq diffs (cadr diff))
          (setq mes (concat mes (format "-%d" (length diffs))))
          (when diffs
            (wl-summary-unset-persistent-mark flag diffs 'no-modeline 'no-server folder))
          (setq diffs (car diff)
                mes (concat mes (format "/+%d %s " (length diffs) flag)))
          (when diffs
            (wl-summary-set-persistent-mark flag diffs 'no-modeline 'no-server folder)))
        (message "wl-summary-sync-marks:  Updating persistent marks (%s) ... done." folder-name)
        (if (interactive-p)
          (message "%s" mes))))
    
    (defsubst wl-summary-set-persistent-mark-internal (inverse
                   flag
                   &optional number-or-numbers
                   no-modeline-update
                   no-server
                   interactive
                   folder) ;; @lawlist added FOLDER argument
      "Set persistent mark."
      (save-excursion
        (let ((folder (or folder wl-summary-buffer-elmo-folder))
              number number-list)
          (setq number-list (cond ((numberp number-or-numbers)
                 (list number-or-numbers))
                ((and (not (null number-or-numbers))
                (listp number-or-numbers))
                 number-or-numbers)
                ((setq number (wl-summary-message-number))
                 ;; interactive
                 (list number))))
          (if (null number-list)
        (message "No message.")
      ;; XXX Only the first element of the list is checked.
      (if (elmo-message-flag-available-p folder (car number-list) flag)
          (progn
            (if inverse
          (elmo-folder-unset-flag folder number-list flag no-server)
        (elmo-folder-set-flag folder number-list flag no-server))
            (unless no-modeline-update
        ;; Update unread numbers.
        ;; should elmo-flag-mark-as-read return unread numbers?
        (wl-summary-count-unread)
        (wl-summary-update-modeline)
        (wl-folder-update-unread
         (wl-summary-buffer-folder-name)
         wl-summary-buffer-unread-count)))
        (if interactive
            (error "Flag `%s' is not available in this folder" flag)))))))
    
    (defun wl-summary-unset-persistent-mark (&optional flag
                   number-or-numbers
                   no-modeline-update
                   no-server
                   folder) ;; @lawlist added the FOLDER argument
      "Unset persistent mark."
      (interactive)
      (when (interactive-p)
        (let ((completion-ignore-case t))
          (setq flag (intern (downcase
            (completing-read
             "Mark name: "
             (mapcar (lambda (flag)
                 (list (capitalize (symbol-name flag))))
               (wl-summary-get-available-flags))
             nil
             'require-match))))))
      (wl-summary-set-persistent-mark-internal 'inverse
                 flag
                 number-or-numbers
                 no-modeline-update
                 no-server
                 (interactive-p)
                 folder))
    
    (defun wl-summary-set-persistent-mark (&optional flag
                 number-or-numbers
                 no-modeline-update
                 no-server
                 folder) ;; @lawlist added the FOLDER argument
      "Set persistent mark."
      (interactive)
      (when (interactive-p)
        (let ((completion-ignore-case t))
          (setq flag (intern (downcase
            (completing-read
             "Mark name: "
             (mapcar (lambda (flag)
                 (list (capitalize (symbol-name flag))))
               (wl-summary-get-available-flags))
             nil
             'require-match))))))
      (wl-summary-set-persistent-mark-internal nil
                 flag
                 number-or-numbers
                 no-modeline-update
                 no-server
                 (interactive-p)
                 folder))

**Comment by ikazuhiro** [comment]
`wl-folder-sync-entity` is used to update displayed information in Folder mode.  I think it does not need to update flag information.  Moreover, it may be called many times at a time and it should not take much time.  Why you don't go into Summary mode on-line?

**Comment by lawlist** [comment]
Thank you for taking a look at issue #142.

After my having spent some additional time examining the code, I can see that you are correct in that what happens in `folder-mode` is primarily designed for the benefit of what happens there (and *not* for the benefit of `summary-mode`).

I had erroneously believed that force-synching and force-prefetching from `folder-mode` (while on-line) would have been sufficient to have `summary-mode` be perfectly up-to-date when viewing off-line.  My goal had been to configure `folder-mode` in such a way that I could update everything while on-line, and then go-off line for the remainder of my Emacs session -- queuing whatever is needed and going on-line at some point in the future.

To the extent that I am a unique fact pattern in terms of wanting to update everything from `folder-mode`, then I certainly understand and it is okay to close out issue #142.

I didn't see a prefetch from `folder-mode` without it opening up a `summary-mode` buffer in the process, so I came up with this little function:

    ;;; EXAMPLE:  (wl-prefetch-entity "%inbox")
    (defun wl-prefetch-entity (folder-or-name)
    "Prefetching everything within entity that is not cached.
    If off-line, then queue the prefetching operatations."
      (let* ((folder
              (if (stringp folder-or-name)
                (wl-folder-get-elmo-folder folder-or-name)
                folder-or-name))
             (uncached-list (elmo-folder-list-flagged folder 'uncached 'in-msgdb)))
        (dolist (number uncached-list)
          (elmo-message-encache folder number)
          (elmo-message-set-cached folder number t))
        ;;; save the queue to the queue file
        (unless wl-plugged
          (elmo-quit))))

And then I put it all together with one function that checks and synchronizes and prefetches one folder at a time without generating a `summary-mode` buffer.

Thanks,

Keith
