### ISSUE TITLE
It is impossible to add a user with an "@" in the username.

### ISSUE THREAD

**Issue by Erk-** [wanderlust/wanderlust#144]
The imap user my provider has made is in the form user@example.com, and I can not add a user like that to the .folders file, What I try
`%inbox:user@example.com/clear@mail.other-example.com`
I have tried to escape it with \ and sorround it with ", but none of that works.

**Comment by j-fu** [comment]
Try
````%inbox:"user@example.com"@mail.other-example.com````

At least this works for me in a similar situation.

**Comment by Erk-** [comment]
Thanks. That works I thought had tried that, but i may have made an error.
