### ISSUE TITLE
mail-yank-hooks is obsolete

### ISSUE THREAD

**Issue by chep** [wanderlust/wanderlust#145]
mail-yank-hooks has been removed on emacs development branch:
http://git.savannah.gnu.org/cgit/emacs.git/commit/?id=72688426cef4e5128ce68f75cb8a3f31572daec0

I got an error while trying to reply to a email because it is used here:
https://github.com/wanderlust/wanderlust/blob/master/wl/wl-draft.el#L537

There are other occurrences on lines 639 and 671 but the variables seem unused.

**Comment by ikazuhiro** [comment]
Shoud be fixed at https://github.com/wanderlust/wanderlust/commit/6aa1a1ea570f3071647bd9d00d99e396156cbdc9 .  Thank you for your report.

> There are other occurrences on lines 639 and 671 but the variables seem unused.

They are let-bound to `nil` to suppress hooks and needed for old platforms.
