### ISSUE TITLE
feature request: custom labels

### ISSUE THREAD

**Issue by oivulf** [wanderlust/wanderlust#147]
Dear Developers,
would it be possible to implement custom labels or marks stored on backend, like "important", "todo" and possibly highlight their occurrences?

**Comment by ikazuhiro** [comment]
Plase search [the document](https://wanderlust.github.io/wl-docs/wl.html) with global-flag and wl-summary-flag-alist variable.

**Comment by oivulf** [comment]
Dear Ikazuhiro,
thank you
