### ISSUE TITLE
global minor modes are not not started

### ISSUE THREAD

**Issue by egh** [wanderlust/wanderlust#150]
Global minor modes are defined using `define-globalized-minor-mode`, which adds a function to start the mode to `after-change-major-mode-hook`.

However, in `wl-draft-create-buffer`, this hook is set to `nil`:

```elisp
    (let (change-major-mode-hook)
      (wl-draft-mode))
```

I am not sure why this is done, but it prevents all globalized minor modes from loading automatically. I tried changing to: `(wl-draft-mode)`(without the `let` binding) and it seems to work.

I discovered this attempting to use `yasnippet` mode, but I assume it is true of all globalized minor modes.

I am not sure if this should be changed, but I thought I'd file an issue.

**Comment by ikazuhiro** [comment]
I've removed let binding of `change-major-mode-hook`.  As far as I investigated, its aim seems to suppress font-lock mode.  But font-lock mode has been already suppressed by another method and probably let-bindings already became be unneeded.

**Comment by egh** [comment]
Wonderful, thank you!
