### ISSUE TITLE
How to set wl-summary-skip-mark-list to nil

### ISSUE THREAD

**Issue by toshjp** [wanderlust/wanderlust#157]
Hello,

Thanks for all the efforts you put in for this project. I have been using wl for quite a while and always happy with it. There is one thing I recently noticed.

In summary view, wl skips messages with marks specified by wl-summary-skip-mark-list while I move around by pressing n or p. When I set wl-summary-skip-mark-list to nil and press these keys, however, wl displays "No more messages. Type SPC to go to folder mode." I would appreciate it if you could look into this problem.

Best regards.

**Comment by ikazuhiro** [comment]
It is a bug of Wanderlust.  Shoud be fixed at https://github.com/wanderlust/wanderlust/commit/b85080963ac680a64eb931c4aa1344d48993c65e.  Please confirm.

**Comment by toshjp** [comment]
I have installed the latest fix and made sure that I can move up and down the summary view by pressing n and p keys. Thanks for your quick response, I really appreciate it.
