### ISSUE TITLE
Does wanderlust support proxy?

### ISSUE THREAD

**Issue by mgcyung** [wanderlust/wanderlust#158]

**Comment by ikazuhiro** [comment]
I have never used proxy.  But AFAIK, Wanderlust should be able to use `socks.el` for POP3, IMAP, NNTP folders.
Use `!socks` suffix in your folder definitions.
```code
%inbox:hoge/clear@server1!socks
```

**Comment by mgcyung** [comment]
> I have never used proxy.  But AFAIK, Wanderlust should be able to use `socks.el` for POP3, IMAP, NNTP folders.
> Use `!socks` suffix in your folder definitions.
> ```code
> %inbox:hoge/clear@server1!socks
> ```

Thanks! I tried ```code %inbox:hoge/clear@server1!socks ```, but there is an error in "elmo-network-initialize-session"
```
Debugger entered--Lisp error: (elmo-open-error elmo-network-initialize-session)
  signal(elmo-open-error (elmo-network-initialize-session))
  wl(nil)
  funcall-interactively(wl nil)
  call-interactively(wl record nil)
  command-execute(wl record)
  helm-M-x(nil #("wl" 0 2 (match-part "wl")))
  funcall-interactively(helm-M-x nil #("wl" 0 2 (match-part "wl")))
  call-interactively(helm-M-x nil nil)
  command-execute(helm-M-x)
```

The socks setting is
``` emacs-lisp
(setq socks-noproxy '("127.0.0.1"))
(setq socks-server '("Default server" "127.0.0.1" 1086 5))
(setq url-gateway-method 'socks)
```
and is works fine for browser and other application.

The folder definitions are

```
GMAIL{
   %INBOX:mgcyung/clear@imap.gmail.com:993!socks         "In"
   %[Gmail]/Sent:mgcyung/clear@imap.gmail.com:993!socks  "Sent"
   %[Gmail]/Draft:mgcyung/clear@imap.gmail.com:993!socks "Draft"
   %[Gmail]/Trash:mgcyung/clear@imap.gmail.com:993!socks "Trash"
   %[Gmail]/Spam:mgcyung/clear@imap.gmail.com:993!socks  "Spam"
}
```

**Comment by mgcyung** [comment]
> Wanderlust seems not to support SSL connection via SOCKS.  Try below with `!!socks` suffix (not tested, requires Built-in GnuTLS library).  Additionally please confirm your server's port is really `1086`.
> ```lisp
> (eval-after-load "elmo-vars"
>   '(progn
>      (add-to-list 'elmo-network-stream-type-alist
> 		  '("!!socks" socks-ssl socks socks-ssl-open-network-stream))
>      (defun socks-ssl-open-network-stream (name buffer host service)
>        (let ((process (socks-open-network-stream name buffer host service)))
> 	 (gnutls-negotiate :process process :hostname host)
>          process))))
> ```

It works. Thanks for helping and the awesome work!

**Comment by mgcyung** [comment]
@ikazuhiro is there a similar setting for draft mode to send a email?

**Comment by ikazuhiro** [comment]
All settings are not tested.

```lisp
;; No encryptoin
(setq wl-smtp-connection-type nil
      smtp-open-connection-function socks-open-network-stream)
```
```lisp
;; SSL
;; Built-in GnuTLS library is required.
;; socks-ssl-open-network-stream is defined in previous comment.
(setq wl-smtp-connection-type nil
      smtp-open-connection-function socks-ssl-open-network-stream)
```
```lisp
;; STARTTLS
;; Built-in GnuTLS library is required.
;; smtp-use-gnutls must be non-nil.
(setq wl-smtp-connection-type 'starttls
      smtp-open-connection-function socks-open-network-stream)
```

**Comment by mgcyung** [comment]
Starttls works for me with two typoes fixed
```
(setq wl-smtp-connection-type 'starttls
      smtp-open-connection-function 'socks-open-network-stream)
```
Thanks for your help.
