### ISSUE TITLE
Make a filter on an email folder

### ISSUE THREAD

**Issue by mgcyung** [wanderlust/wanderlust#161]
It says "no folder" when making a filter ("m f") on an email folder. 

The folder-path is nil after the following code  on an email folder
```
      (setq folder-path (wl-fldmgr-get-path wl-folder-entity
					    (wl-folder-get-entity-from-buffer)
;;;					    (wl-fldmgr-get-entity-id)
					    group-target))
```

**Comment by ikazuhiro** [comment]
As far as I tested, the message is shown only when making filter from blank line.  Which type of folder you tried?

**Comment by mgcyung** [comment]
It on a gmail folder. But it works now. Sorry for borthering.
