### ISSUE TITLE
elmo-imap4-folder-name-syntax doesn't allow multi-domain IMAP host

### ISSUE THREAD

**Issue by levitte** [wanderlust/wanderlust#162]
There's a form of multi domain IMAP host where the user is identified as its full email address, i.e. the username is "user@userdomain.whatever".  In `.folders`, a folder group for that user's account would be something like this:

```
%:user@userdomain.whatever/login@host:993! /
```

Unfortunately, `elmo-imap4-folder-name-syntax` doesn't allow that, since the @ isn't part of its regexp.  I imagine, but haven't really tested this yet, that modifying it to include @ could fix this issue.  I have no idea, though, what the implications would be elsewhere...

**Comment by egh** [comment]
@levitte You should be able to quote the username, e.g. `%:"user@userdomain.whatever"/login@host:993!`

**Comment by levitte** [comment]
Oh!  Ok, will try that.

**Comment by levitte** [comment]
Yup, that worked.  Never mind then, and thank you!

**Comment by egh** [comment]
No problem! Glad it worker.
