### ISSUE TITLE
IMAP Failure

### ISSUE THREAD

**Issue by nshi** [wanderlust/wanderlust#166]
I ran into the following error when starting WL after moving my emacs config from an old Mac running Mojave to a new machine running Mojave. Does anyone have any insights into what might be causing it?

Auto plugged off at imap.gmail.com:993 :elmo-network-initialize-session
helm-M-x: Cannot open: elmo-network-initialize-session

I installed emacs using `brew cask install emacs`. I also tried [emacs-plus](https://github.com/d12frosted/homebrew-emacs-plus). Both have the same issue.

Thanks,

**Comment by tats** [comment]
If you use Emacs 26.1 or 26.2, add "-VERS-TLS1.3" to
gnutls-algorithm-priority due to Emacs bug #34341.

  - 26.1; url-retrieve-synchronously returns blank buffer
    https://debbugs.gnu.org/cgi/bugreport.cgi?bug=34341

e.g.
```
(setq gnutls-verify-error t)
(setq gnutls-min-prime-bits 1024)
(setq gnutls-algorithm-priority "SECURE128:-VERS-SSL3.0:-VERS-TLS1.3")
```

**Comment by nshi** [comment]
Thank you, @tats. That solved the issue.
