### ISSUE TITLE
Cannot send with `wl-draft-send-mail-with-smtp' when running byte-compiled

### ISSUE THREAD

**Issue by dmj** [wanderlust/wanderlust#177]
I use `wl-template-alist' with templates for personal/professional email

```
(setq wl-template-alist '(
                       ("personal"
                        (wl-from . "David Maus <dmaus@dmaus.name>")
                        (wl-smtp-posting-server . "mx2f41.netcup.net")
                        (wl-smtp-posting-port . 587)
                        (wl-smtp-posting-user . "dmaus@dmaus.name")
                        (wl-smtp-authenticate-type . "plain")
                        (wl-smtp-connection-type . 'starttls)
                        (mail-signature-file . (expand-file-name "signature/dmaus.name" user-emacs-directory))
                        ("Fcc" . "%Inbox:\"dmaus@dmaus.name\"/clear@mx2f41.netcup.net:993!")
                        ("From" . wl-from))
                       ("work"
                        (wl-from . "David Maus <david.maus@sub.uni-hamburg.de>")
                        (wl-smtp-posting-server . "exchange.uni-hamburg.de")
                        (wl-smtp-posting-port . 587)
                        (wl-smtp-posting-user . "X")
                        (wl-smtp-authenticate-type . "login")
                        (wl-smtp-connection-type . 'starttls)
                        (mail-signature-file . (expand-file-name "signature/sub.uni-hamburg.de" user-emacs-directory))
                        ("Fcc" . "%Inbox:\"X\"/clear@exchange.uni-hamburg.de:993!")
                        ("From" . wl-from)
                        ("Organization" . "Staats- und Universitaetsbibliothek Hamburg"))))
```

I draft a message, select the identity "work". When I try to send the message I get the following backtrace:

```
Debugger entered--Lisp error: (error "‘smtp-server’ not defined")
  signal(error ("‘smtp-server’ not defined"))
  wl-draft-send-mail-with-smtp()
  wl-draft-dispatch-message()
  wl-draft-normal-send-func(#<buffer .drafts/2853> t)
  wl-draft-send(t)
  wl-draft-send-and-exit()
  funcall-interactively(wl-draft-send-and-exit)
  call-interactively(wl-draft-send-and-exit nil nil)
  command-execute(wl-draft-send-and-exit)
```

The error seems to be here in `wl-draft-send-mail-with-smtp':

```
     (let* (...
	 (smtp-server
	  (or wl-smtp-posting-server smtp-server "localhost"))
```

The variable `wl-smtp-posting-server' is buffer-local in the draft but not dynamically scoped when `wl-draft-send-mail-with-smtp' executes.

This is only the case if I run the byte-compiled version. If I eval the defun everything works as expected.

**Comment by ikazuhiro** [comment]
Not reproducible for me.

The error occurs in `smtp-send-buffer` function only when `smtp-server` is `nil`, but it seems that `wl-draft-send-mail-with-smtp` never sets `smtp-server` to `nil` whatever `wl-smtp-posting-server`'s value is.  `smtp-server` should be set to `"localhost"` in fallback case (according to the code you quoted).  Could you try to re-install FILM, SEMI and Wanderlust?

**Comment by dmj** [comment]
I re-installed the FLIM, SEMI and Wanderlust and the error went away. Thanks for checking!

**Comment by FirstLoveLife** [comment]
@ikazuhiro I have this issue if using native-comp branch.

**Comment by ikazuhiro** [comment]
Confirmed.  The problem disappears when wl-draft.el is not native compiled even if on native-comp branch.  As workaround, please suppress native compiling of `wl-draft.el`.

```elisp
(when (require 'comp nil t)
  ;; You need remove native compiled file (.eln file) for wl-draft.el
  ;; manually.
  (add-to-list 'comp-deferred-compilation-black-list "wl-draft\\.el"))
```

**Comment by ikazuhiro** [comment]
This problem should be fixed at https://github.com/wanderlust/wanderlust/commit/c19a1df3ea4256519619de0a882122cd3b2396c6 .
Please see https://github.com/wanderlust/wanderlust/pull/189 for details.
