### ISSUE TITLE
Wanderlust crashes when searching Summary

### ISSUE THREAD

**Issue by wiz21b** [wanderlust/wanderlust#179]
Hello,

When I'm the Summary buffer of my INBOX, if I perform a regular string search (Ctrl-s), then WL finds the first occurence of my search. On the second Ctrl-s hit, it doesn't find the second occurence and crashes (i.e. emacs closes without message).

My emacs is : GNU Emacs 26.1 (build 2, x86_64-pc-linux-gnu, GTK+ Version 3.24.5) of 2019-09-23, modified by Debian
My WL is  version 2.15.9 - "Almost Unreal"; installed from MELP IIRC.

My inbox is rather big : 15000+ messages.

I have tuned WL a bit, but nothing fancy I guess.

Too bad it crashes, 'cos WL is otherwise snappy and efficient for my way of working.

Stéphane.

**Comment by wiz21b** [comment]
Additional information, when I perform a similar search on my "Sent" folder, it works fine. The sent folder contains about 5000 messages (3x less than my inbox)

**Comment by ikazuhiro** [comment]
Not reproducible for me.  I can search in Summary buffer which has over 250k messages.  Generally speaking, it would be Emacs's issue that elisp program could crash emacs.  Furthermore, `C-s` in Summary buffer runs Emacs's search command, which is not Wanderlust specific.

1. Confirm whether emacs really crashes by starting emacs from terminal.
2. Directly open correspoding summary cache (`.wl-summary-cache` file in `~/.elmo`'s subdirectory) and search string.  If emacs crashes, Wanderlust is not related.
3. Run emacs in terminal (`emacs -nw`) and confirm whether emacs crashes.  If Emacs doesn't crash, the problem would be Emacs's GUI related issue.

**Comment by wiz21b** [comment]
This bug didn't appear for months, not a nuisance at all.
