### ISSUE TITLE
Symbol’s function definition is void: elmo-replace-in-string

### ISSUE THREAD

**Issue by tyoshiko** [wanderlust/wanderlust#182]
I cannot open my folder list with the message shown in the title, after updating to wanderlust-20200822.850 from MELPA. The Backtrace is as follows:

Debugger entered--Lisp error: (void-function elmo-replace-in-string)                                                                                           
  signal(void-function (elmo-replace-in-string))                                                                                                               
  wl(nil)                                                                                                                                                      
  funcall-interactively(wl nil)                                                                                                                                
  call-interactively(wl record nil)                                                                                                                            
  command-execute(wl record)                                                                                                                                   
  execute-extended-command(nil "wl" "wl")                                                                                                                      
  funcall-interactively(execute-extended-command nil "wl" "wl")                                                                                                
  call-interactively(execute-extended-command nil nil)                                                                                                         
  command-execute(execute-extended-command)                                                                                                                    

Can anyone fix it? I have been using wl for long time (thanks a lot) but not seen this kind of issue.

**Comment by tats** [comment]
It seems portions of your wanderlust are byte-compiled with old elmo-date.el.

Probably, removing wanderlust and then installing wanderlust may fix the issue,
though I don't know the real solution of this MELPA package issue.

**Comment by tats** [comment]
> removing wanderlust and then installing wanderlust

removing wanderlust, restarting Emacs and then installing wanderlust

**Comment by tyoshiko** [comment]
That successfully fixed the issue. Thank you very much.
