### ISSUE TITLE
charset is incorrect when automatically displaying all your IMAP folders

### ISSUE THREAD

**Issue by FirstLoveLife** [wanderlust/wanderlust#187]
I found wanderlust can display all my imap folders via `/`, e.g., 
```
    %:"firstlovelife@aliyun.com"/clear@imap.aliyun.com:993!/
```
but it doesn't set correct charset for these folder name: 
```
     [-]%:"firstlovelife@aliyun.com"/clear@imap.aliyun.com:993!:0/0/0
       %�����ʼ�:"firstlovelife@aliyun.com"@imap.aliyun.com:993!:0/*/0
       %�ѷ���:"firstlovelife@aliyun.com"@imap.aliyun.com:993!:*/*/*
       %INBOX:"firstlovelife@aliyun.com"@imap.aliyun.com:993!:*/*/*
       %�ݸ�:"firstlovelife@aliyun.com"@imap.aliyun.com:993!:0/*/0
       %��ɾ���ʼ�:"firstlovelife@aliyun.com"@imap.aliyun.com:993!:*/*/*
```

If I set imap folder manually, charset is ok: 
```
	%已归档:"chenli@uniontech.com"/clear@imap.263.net:143	"已归档"
	%已发送:"chenli@uniontech.com"/clear@imap.263.net:143	"已发送"
	%INBOX:"chenli@uniontech.com"/clear@imap.263.net:143	"收件箱"
	%垃圾邮件:"chenli@uniontech.com"/clear@imap.263.net:143	"垃圾邮件"
```
shows 
```
     已归档:*/*/*
     已发送:*/*/*
     收件箱:0/0/0
     垃圾邮件:*/*/*
```

I have set `(setq wl-mime-charset 'gbk)`, but nothing changes.

**Comment by ikazuhiro** [comment]
Not reproducible for me.  I can see Japanese folder names correctly on Gmail and Outlook.com's IMAP server.  I can't expect the cause of your problem at present.

1. Your listed subfolders don't have authentication type (`/clear`). that is just miscopied?

2. Retry subfolder listing (open root IMAP folder by `C-u SPC`) after `(setq elmo-imap4-debug t)`.  Debugging buffer named `*IMAP4 DEBUG*` should be made, so please confirm result of list command.  Here is my result on Gmail.

```
[18:21:38] <-- elmo-imap45 list "" *
[18:21:39] -> * LIST (\HasNoChildren) "/" "INBOX"
[18:21:39] -> * LIST (\HasChildren \Noselect) "/" "[Gmail]"
[18:21:39] -> * LIST (\All \HasNoChildren) "/" "[Gmail]/&MFkweTBmMG4w4TD8MOs-"
[18:21:39] -> * LIST (\HasNoChildren \Trash) "/" "[Gmail]/&MLQw33ux-"
[18:21:39] -> * LIST (\Flagged \HasNoChildren) "/" "[Gmail]/&MLkwvzD8TtgwTQ-"
[18:21:39] -> * LIST (\Drafts \HasNoChildren) "/" "[Gmail]/&Tgtm+DBN-"
[18:21:39] -> * LIST (\HasNoChildren \Junk) "/" "[Gmail]/&j,dg0TDhMPww6w-"
[18:21:39] -> * LIST (\HasNoChildren \Sent) "/" "[Gmail]/&kAFP4W4IMH8w4TD8MOs-"
[18:21:39] -> * LIST (\HasNoChildren \Important) "/" "[Gmail]/&kc2JgQ-"
[18:21:39] -> elmo-imap45 OK Success
```

3. If poossible, comfirm your subfoldeers's names by other client (WEB interface, other application).

**Comment by FirstLoveLife** [comment]
> Not reproducible for me. I can see Japanese folder names correctly on Gmail and Outlook.com's IMAP server. I can't expect the cause of your problem at present.
> 
> 1. Your listed subfolders don't have authentication type (`/clear`). that is just miscopied?
> 2. Retry subfolder listing (open root IMAP folder by `C-u SPC`) after `(setq elmo-imap4-debug t)`.  Debugging buffer named `*IMAP4 DEBUG*` should be made, so please confirm result of list command.  Here is my result on Gmail.
> 
> ```
> [18:21:38] <-- elmo-imap45 list "" *
> [18:21:39] -> * LIST (\HasNoChildren) "/" "INBOX"
> [18:21:39] -> * LIST (\HasChildren \Noselect) "/" "[Gmail]"
> [18:21:39] -> * LIST (\All \HasNoChildren) "/" "[Gmail]/&MFkweTBmMG4w4TD8MOs-"
> [18:21:39] -> * LIST (\HasNoChildren \Trash) "/" "[Gmail]/&MLQw33ux-"
> [18:21:39] -> * LIST (\Flagged \HasNoChildren) "/" "[Gmail]/&MLkwvzD8TtgwTQ-"
> [18:21:39] -> * LIST (\Drafts \HasNoChildren) "/" "[Gmail]/&Tgtm+DBN-"
> [18:21:39] -> * LIST (\HasNoChildren \Junk) "/" "[Gmail]/&j,dg0TDhMPww6w-"
> [18:21:39] -> * LIST (\HasNoChildren \Sent) "/" "[Gmail]/&kAFP4W4IMH8w4TD8MOs-"
> [18:21:39] -> * LIST (\HasNoChildren \Important) "/" "[Gmail]/&kc2JgQ-"
> [18:21:39] -> elmo-imap45 OK Success
> ```
> 
> 3. If poossible, comfirm your subfoldeers's names by other client (WEB interface, other application).

1. these subfolders do have no auth type. 

2.
```
[09:13:52] <-- elmo-imap43 capability
[09:13:52] -> * CAPABILITY IMAP4 IMAP4rev1 XLIST ID STARTTLS UIDPLUS
[09:13:52] -> elmo-imap43 OK CAPABILITY Completed
*elmo-imap43* OK arrived
[09:13:52] => ((ok nil) (capability (imap4 imap4rev1 xlist id starttls uidplus)))
[09:13:52] -> mailbox size adjusted: nil, (nil)
[09:13:52] <-- elmo-imap44 list "" *
[09:13:52] -> * LIST () "/" "INBOX"
[09:13:52] -> * LIST () "/" "INBOX/Trash"
[09:13:52] -> * LIST (\Sent) "/" "&XfJT0ZAB-"
[09:13:52] -> * LIST (\Trash) "/" "&XfJSIJZk-"
[09:13:52] -> * LIST (\Drafts) "/" "&g0l6P3ux-"
[09:13:52] -> * LIST (\Junk) "/" "&V4NXPpCuTvY-"
[09:13:52] -> * LIST () "/" "&XfJfUmhj-"
[09:13:52] -> * LIST () "/" "Sent Mail"
[09:13:52] -> * LIST () "/" "Archives"
[09:13:52] -> * LIST () "/" "Spam"
[09:13:52] -> * LIST () "/" "Drafts"
[09:13:52] -> * LIST () "/" "&XfJfUmhj-"
[09:13:52] -> * LIST () "/" "&V4NXPpCuTvY-"
[09:13:52] -> * LIST () "/" "&ZTZO9nux-"
[09:13:52] -> * LIST () "/" "alpha"
[09:13:52] -> * LIST () "/" "linux-alpha"
[09:13:52] -> * LIST () "/" "linux-alpha-fuck"
[09:13:52] -> * LIST () "/" "openssh"
[09:13:52] -> * LIST () "/" "openssh-fuck"
[09:13:52] -> * LIST () "/" "ltp-try"
[09:13:52] -> * LIST () "/" "&V4NXPpCuTvY-"
[09:13:52] -> elmo-imap44 OK LIST Completed
*elmo-imap44* OK arrived
```
3. 
![image](https://user-images.githubusercontent.com/37442588/97649086-6743aa80-1a91-11eb-876f-5101ab46c7d8.png) Yes, they display correctly in web interface

**Comment by ikazuhiro** [comment]
Thank you.  It seems that the server has no problem.  Listed subfolders don't have auth type which is the same as `elmo-imap4-default-authenticate-type`.

1. Does your problem also happens on other server?  If not sure, add entry `~/.folders` such as `%:"chenli@uniontech.com"/clear@imap.263.net:143/` and get subfolders.

2. Are the subfolder which has mis-decoded name accessible?  Can you enter the subfolder and get messages?

3. Check modified utf-7 decoder.  Try below code in `*scratch*` buffer and confirm result.  It should return string `"已发送 已删除 草稿箱 垃圾邮件 已归档 已归档 垃圾邮件 收件箱 垃圾邮件"`.

```elisp
(decode-coding-string
 (mapconcat
  'identity
  '("&XfJT0ZAB-" "&XfJSIJZk-" "&g0l6P3ux-" "&V4NXPpCuTvY-" "&XfJfUmhj-"
    "&XfJfUmhj-" "&V4NXPpCuTvY-" "&ZTZO9nux-" "&V4NXPpCuTvY-")
  " ")
 'utf-7-imap)
```

4. Can you upload (or send me) folder list file?  It should be `~/.elmo/folder/%___Q_firstlovelife@aliyun.com_Q_ clear@imap.aliyun.com__993!/flist`.

**Comment by FirstLoveLife** [comment]
> Thank you. It seems that the server has no problem. Listed subfolders don't have auth type which is the same as `elmo-imap4-default-authenticate-type`.
> 
>     1. Does your problem also happens on other server?  If not sure, add entry `~/.folders` such as `%:"chenli@uniontech.com"/clear@imap.263.net:143/` and get subfolders.
> 
>     2. Are the subfolder which has mis-decoded name accessible?  Can you enter the subfolder and get messages?
> 
>     3. Check modified utf-7 decoder.  Try below code in `*scratch*` buffer and confirm result.  It should return string `"已发送 已删除 草稿箱 垃圾邮件 已归档 已归档 垃圾邮件 收件箱 垃圾邮件"`.
> 
> 
> ```emacs-lisp
> (decode-coding-string
>  (mapconcat
>   'identity
>   '("&XfJT0ZAB-" "&XfJSIJZk-" "&g0l6P3ux-" "&V4NXPpCuTvY-" "&XfJfUmhj-"
>     "&XfJfUmhj-" "&V4NXPpCuTvY-" "&ZTZO9nux-" "&V4NXPpCuTvY-")
>   " ")
>  'utf-7-imap)
> ```
> 
>     4. Can you upload (or send me) folder list file?  It should be `~/.elmo/folder/%___Q_firstlovelife@aliyun.com_Q_ clear@imap.aliyun.com__993!/flist`.

1. Yes. all my chinese mail have this problem
2. They are accessible and can get messages
3. the string `"已发送 已删除 草稿箱 垃圾邮件 已归档 已归档 垃圾邮件 收件箱 垃圾邮件"` is returned correctly. 
4. Sure. Because I have switch my aliyun mail language to email, so they are all english folder now. I have create two new chinese folder for testing: 
![image](https://user-images.githubusercontent.com/37442588/97772209-c41d8e80-1b7f-11eb-93bd-2b87331b850a.png)

```
firstlove@manjaro ~> cat .elmo/folder/\%___Q_firstlovelife@aliyun.com_Q_\ clear@imap.aliyun.com__993!/flist
;;; -*- mode: emacs-lisp; coding: us-ascii -*-
(("%&XwBT0Q-:\"firstlovelife@aliyun.com\"@imap.aliyun.com:993!" "%&bUuL1Q-:\"firstlovelife@aliyun.com\"@imap.aliyun.com:993!" "%Spam:\"firstlovelife@aliyun.com\"@imap.aliyun.com:993!" "%Sent:\"firstlovelife@aliyun.com\"@imap.aliyun.com:993!" "%Draft:\"firstlovelife@aliyun.com\"@imap.aliyun.com:993!" "%Trash:\"firstlovelife@aliyun.com\"@imap.aliyun.com:993!" "%INBOX:\"firstlovelife@aliyun.com\"@imap.aliyun.com:993!") nil)⏎ 
```

**Comment by tats** [comment]
>        %�ѷ���:"firstlovelife@aliyun.com"@imap.aliyun.com:993!:*/*/*
It seems GB2312 encoded '已发送' is incorrectly decoded as UTF-8.

I've found a long standing bug that elmo-object-load doesn't detect
the coding cookie in the folder list file.  If I revert the commit
<https://github.com/wanderlust/wanderlust/commit/ca90080da788032783940a9eb98db7009e0c4b83>,
it seems to work.

On 2005-04-12 at 01:34, [Wanderlust:13620], Hiroya Murata wrote:
> ファイル内に coding system の指定がなく, 函数呼び出しでも MIME
> charset の指定がされていなかった場合には, デコードしてはいけなかっ
> たのをすっかり忘れていました.
> 
> と言う理由で一寸変更させて頂きました.

Though the commit seems intentional, I doubt whether it's correct.

**Comment by ikazuhiro** [comment]
Try [patch](https://gist.github.com/ikazuhiro/5351b170b095cab07cdc784372411ced) without revert.  But so if the revert would fix the problem, subfolders's name should be displayed correctly just after re-listing (open root IMAP folder by C-u SPC) and wrongly dispplayed in the next session.  Is it correct?

**Comment by tats** [comment]
> Try patch without revert.

Looks fine for me.

> wrongly dispplayed in the next session. Is it correct?

Yes, in my case.

**Comment by FirstLoveLife** [comment]
@ikazuhiro Hi, I have update to 11dc2b8, but this problem still exist for me.

**Comment by ikazuhiro** [comment]
If you get wrongly displayed subfolder names even just after re-listing, the commit would be unrelated with your problem.  As @tats says it seems that wrong string is encoded in GB2312 and misdecoded UTF-8.  But such code conversion should not occur while re-listing.  So I can't still understand  what happens in your Emacs.

1. According to your comment, subfolder name contains `�`.  But if Emacs converted the string, it should have contained unprintable eight-bit characters.  Is `�` really displayed in Emacs?  If not, how displayed in Emacs?

2. After re-listing, please quit Wanderlust and Emacs with the latest Wanderlust, and then retry to upload folder list file (`~/.elmo/folder/%___Q_firstlovelife@aliyun.com_Q_ clear@imap.aliyun.com__993!/flist`).  Your uploaded file contains modified utf-7 string (such as `&XwBT0Q-`), that is very odd.  IMAP folder name in `flist` file shoud be decoded.

**Comment by FirstLoveLife** [comment]
> If you get wrongly displayed subfolder names even just after re-listing, the commit would be unrelated with your problem. As @tats says it seems that wrong string is encoded in GB2312 and misdecoded UTF-8. But such code conversion should not occur while re-listing. So I can't still understand what happens in your Emacs.
> 
>     1. According to your comment, subfolder name contains `�`.  But if Emacs converted the string, it should have contained unprintable eight-bit characters.  Is `�` really displayed in Emacs?  If not, how displayed in Emacs?
> 
>     2. After re-listing, please quit Wanderlust and Emacs with the latest Wanderlust, and then retry to upload folder list file (`~/.elmo/folder/%___Q_firstlovelife@aliyun.com_Q_ clear@imap.aliyun.com__993!/flist`).  Your uploaded file contains modified utf-7 string (such as `&XwBT0Q-`), that is very odd.  IMAP folder name in `flist` file shoud be decoded.

char like `�` is not displayed in my emacs any more. I forget when they disappeared. they are displayed as the same string(`%&bUuL1Q-` and  `%&XwBT0Q-`) as below

```
firstlove@manjaro ~> cat ~/.elmo/folder/%___Q_firstlovelife@aliyun.com_Q_\ clear@imap.aliyun.com__993!/flist
;;; -*- mode: emacs-lisp; coding: us-ascii -*-
(("%&bUuL1Q-:\"firstlovelife@aliyun.com\"@imap.aliyun.com:993!" "%&XwBT0Q-:\"firstlovelife@aliyun.com\"@imap.aliyun.com:993!" "%Spam:\"firstlovelife@aliyun.com\"@imap.aliyun.com:993!" "%Sent:\"firstlovelife@aliyun.com\"@imap.aliyun.com:993!" "%INBOX:\"firstlovelife@aliyun.com\"@imap.aliyun.com:993!" "%Draft:\"firstlovelife@aliyun.com\"@imap.aliyun.com:993!" "%Trash:\"firstlovelife@aliyun.com\"@imap.aliyun.com:993!") nil)
```

**Comment by ikazuhiro** [comment]
Probably you set `elmo-imap4-use-modified-utf7` variable to `nil` somewhere.  Its default value is `t`.  Please find your customization and revert to default value.

**Comment by FirstLoveLife** [comment]
Thanks！this problem disappear after removing this (setq elmo-imap4-use-modified-utf7 nil)

**Comment by Reagannnnnn** [comment]
I have a question same with you.but i can't find the `setq elmo-imap4-use-modified-utf7 nil`

**Comment by FirstLoveLife** [comment]
> I have a question same with you.but i can't find the `setq elmo-imap4-use-modified-utf7 nil`

what's your elmo-imap4-use-modified-utf7?
