### ISSUE TITLE
Does wanderlust support oauth2?

### ISSUE THREAD

**Issue by FirstLoveLife** [wanderlust/wanderlust#190]
I registered yahoo recently and found it can only be authorized by oauth2 from thunderbird. I cannot find any oauth-related things mentioned in wanderlust's code and doc.

**Comment by ikazuhiro** [comment]
Wanderlust should be able to do xoauth2 authentication method with [FLIM-LB](https://github.com/wanderlust/flim).  Actually, I can access to google.com and outlook.com.

1. Install oauth2 package (available at ELPA) and configure browse-url
and plstore to work with oauth2 package appropriately.

2. Register Wanderlust and get your client ID and secret.  See https://developer.yahoo.com/oauth2/guide/openid_connect/getting_started.html for details.  I don't have account of yahoo.com, so I can't help you about this step.

3.  Set `sasl-xoauth2-host-url-table` variable.  See below example (not tested).

```elisp
(eval-after-load "sasl-xoauth2"
  '(progn
     (add-to-list 'sasl-xoauth2-host-url-table
		  ;; yahoo.com
		  '("yahoo\\.com$"
		    "https://api.login.yahoo.com/oauth2/request_auth"
		    "https://api.login.yahoo.com/oauth2/get_token"
		    "mail-w"
		    ;; You may need redirect-uri such as
		    ;; "http://localhost/result"
		    nil))))
```

4. set `sasl-xoauth2-host-user-id-table` variable. See it's docstring and `sasl-xoauth2.el`'s comment.

```elisp
;; ~/.wl
(setq sasl-xoauth2-host-user-id-table
      `(("\\.yahoo\\.com$"
	 ,(concat "^" (regexp-quote "your_yahoo_ID") "$")
	 "your_client_ID"
	 "your_client_secret")))
```

4. Add folder entry which has `xoauth2` authentication type in `~/.folders`.  Here is example for Gmail.

```
%:your_account/xoauth2@imap.gmail.com:993!/
```

**Comment by FirstLoveLife** [comment]
Thanks!
