### ISSUE TITLE
davmail connection

### ISSUE THREAD

**Issue by fab6** [wanderlust/wanderlust#193]
Hi,

I would like to connect wanderlust to my davmail ms exchange connection. With thunderbird I could easily connect:

[http://davmail.sourceforge.net/thunderbirdimapmailsetup.html](http://davmail.sourceforge.net/thunderbirdimapmailsetup.html)

I tried this small setup 

(setq elmo-imap4-default-server "localhost"
      elmo-imap4-default-user "fbraenns"
      elmo-imap4-default-authenticate-type 'clear
      elmo-imap4-default-port '1143
      elmo-imap4-default-stream-type 'plain
      elmo-imap4-use-modified-utf7 t)

;; SMTP
(setq wl-smtp-connection-type 'starttls
      wl-smtp-posting-port 1025
      wl-smtp-authenticate-type "plain"
      wl-smtp-posting-user "fbraenns"
      wl-smtp-posting-server "localhost"
      wl-message-id-domain "localhost")

Unfortunately I get not connection:

Authetication is failed
helm-M-x-execute-command: Login failed: elmo-imap4-clear-login

Does anyone have an idea or hint, what I am doing wrong?
Thank you in advance!
Fab

**Comment by ikazuhiro** [comment]
Please set `elmo-imap4-debug` to `t` and retry to connect.  And then show the content of `*IMAP4 DEBUG*` buffer.


Below comments whould be not directly related with your current problem.  But I think it should be corrected.

1. `elmo-imap4-default-port` should be a integer.
2. `elmo-imap4-default-stream-type` should be `nil` for direct unencrypted connection.
3. You don't need to set `elmo-imap4-use-modified-utf7`.

```elisp
(setq elmo-imap4-default-user "fbraenns"
      elmo-imap4-default-authenticate-type 'clear
      elmo-imap4-default-port 1143
      ;; Not changed from their default values.
      elmo-imap4-default-server "localhost"
      elmo-imap4-default-stream-type nil
      elmo-imap4-use-modified-utf7 t)
```

4. You don't need to set `wl-message-id-domain` unless you know what you are doing.

**Comment by fab6** [comment]
Thank you for your quick help!

I did some further testing in between and I could send a test mail to my gmail account using the davmail account.

Now after a few further testing this is not working anymore and I do not get any IMAP4 DEBUG buffer anymore.

I mainly get this error message; either with your proposed setq in step 3 or another test where I set the default user to my davmail users account:

`Uncheck(unplugged) "nil"`
It seems that I get this only with your debug elmo-imap4-debug setting.

Without any question about the password I get now this:

![image](https://user-images.githubusercontent.com/3047695/101929025-9bed6a80-3bd6-11eb-96a5-43c06838a681.png)


Before I got at least the prompt to write my passord, this does not happen anymore.
Could it be that there are some cache settings from wl, which I need to erase?

When I want to write a mail now I get:
![image](https://user-images.githubusercontent.com/3047695/101929411-17e7b280-3bd7-11eb-9b93-ae3aad6d2656.png)

... hm, I did something strange!?

**Comment by ikazuhiro** [comment]
> further testing

Describe what you did concretely.  I think no one can understand what happened.


To receive mails and to send mails are basically independent issues.  The former is IMAP related issue and the latter is SMTP related.  I recommend you to resolve issues one by one.

1. The first image seems that you don't describe any folder in `~/.folders`.  What you wrote in the file?

2. I don't understand what's matter in the second image.  Please elaborate.

**Comment by fab6** [comment]
Ok, thank you! Reading works now, but the sending is still not going.

1. I have access now for reading; I somehow commented out the folders file.

2. The second picture describes what happens, when I try to send a mail by pressing C-c C-c or using the menu. Another buffer is popping up below my text message (this small popping up buffer is seen in the picture) and any further keybinding just gets added to the list in the minor buffer, e.g. pressing return a couple times looks like this:
![image](https://user-images.githubusercontent.com/3047695/101985428-3c4f9780-3c88-11eb-96a0-7d2eab68b787.png)

I'm using spacemacs/evil; not sure if this has any impact on the error.
Thank you again!

**Comment by ikazuhiro** [comment]
Wanderlust shows preview of message and related attributes (with another buffer) before actual sending in default settings.  And prompt such as `Send current draft? <y/n/SPC(down)/BS(up)> ` should be showed in minibuffer to confirm for sending.  If it doesn't appear in minibuffer, I don't know the reason.  But please try `y` to send the message.

**Comment by fab6** [comment]
ok, I got it now, thank you very much for your patience! The from address was still wrong and the "send current draft..." was not readable for me.
Thank you very much!
