### ISSUE TITLE
Error: Cannot open load file: No such file or directory, spamfilter

### ISSUE THREAD

**Issue by damon-kwok** [wanderlust/wanderlust#202]
```elisp
In toplevel form:
elsp-spamfilter.el:36:1:Error: Cannot open load file: No such file or directory, spamfilter
```
Where is the `spamfilter.el`?

**Comment by ikazuhiro** [comment]
The author's site has gone.  You can download spamfilter-1.1.tar.gz from [Internet Archive](https://web.archive.org/web/20190326203214/http://www.geocities.co.jp:80/SiliconValley-PaloAlto/7043/) (Japanese).  But it was released at 2004, I don't know if it woks well on recent Emacsen.

**Comment by damon-kwok** [comment]
Thanks for your help :)
