### ISSUE TITLE
wl-score-insert-header broken with score by thread

### ISSUE THREAD

**Issue by LdBeth** [wanderlust/wanderlust#207]
When apply a score file that includes something like a "thread" entry, `elmo-message-entity-field` would look up for `References` header that would return a list of strings as the result, which would cause a type error to be reported when `wl-score-insert-header` tries to call `insert` that list.

I think this may be fixed by something like:
```
	  (setq this (wl-score-ov-entity-get (car art)
					     wl-score-index
					     extra-header))
-	  (when (stringp this)
-	    (setq this (std11-unfold-string this)))
+         (cond ((stringp this)
+	         (setq this (std11-unfold-string this)))
+               ((listp this)
+                (setq this (mapconcat #'std11-unfold-string this " "))))
```

**Comment by ikazuhiro** [comment]
Thank you, committed as you wrote.
