### ISSUE TITLE
wl should support oauth2 (feature request)

### ISSUE THREAD

**Issue by wom-bat** [wanderlust/wanderlust#208]
Now that both Gmail and Microsoft require 2FA using OAUTH2, we need a way to use it for authentication, for both IMAP and SMTP, if we're to keep using WL to read/write emails using these providers.  

There is an oauth2.el package that may be a starting point.

**Comment by ikazuhiro** [comment]
Wanderlust can use oauth2, though you need to obtain your own client ID and secret.
See https://github.com/wanderlust/wanderlust/issues/190 .

**Comment by wom-bat** [comment]
OK so the issue is it needs to be documented.  Plus how can I make it work if I have no access to the Azure portal to create a client ID?
