### ISSUE TITLE
Frozen when imap ccess group has name 

### ISSUE THREAD

**Issue by catap** [wanderlust/wanderlust#216]
Let assume a quite trivial `~/folders.wl`:
```
In {
  %INBOX:"kirill@korins.ky"/plain@mx.catap.net:993! "Personal"
}
%:"kirill@korins.ky"/plain@mx.catap.net:993!/       "All personal"
```

If I remove `"All personal"` everything works as expected. When it has, it stuck on `Checking "%:"kirill@korins.ky"/plain@mx.catap.net:993!/"`.

I'm using 394a46ceb2ccd8204baddedfef27a056afc8aca3 as local root.

**Comment by catap** [comment]
Thus,
```
%:"kirill@korins.ky"/plain@mx.catap.net:993!/       # "All personal"
```
doesn't work neither.

**Comment by ikazuhiro** [comment]
They are features.  Access group and folder nickname can't be defined in the same line.  Please try below.

```
%:"kirill@korins.ky"/plain@mx.catap.net:993!/
=	%:"kirill@korins.ky"/plain@mx.catap.net:993!	"All personal"
```

**Comment by catap** [comment]
@ikazuhiro thanks, it's works.

Maybe it worth to add to a doc?

Also, I feel that I haven't understand how to make hierarchy from access group.

Here I mean that I do have a hierarchy inside imap folders which is shown as:
```
%Archive.Project1:"kirill@korins.ky"/plain@mx.catap.net:993!
%Archive.Project2:"kirill@korins.ky"/plain@mx.catap.net:993!
%Archive.Project2.SubProject1:"kirill@korins.ky"/plain@mx.catap.net:993!
%Archive:"kirill@korins.ky"/plain@mx.catap.net:993!
```

am I right that it is impossible to have nice hierarhy here automatically and I should make it by hand in `folders.wl`?
