### ISSUE TITLE
feature request: global search for a flag

### ISSUE THREAD

**Issue by catap** [wanderlust/wanderlust#217]
From documentation I understand that I may add a filter like `/flag:XXX/%inbox` which filters all messages from that folder which has flag `XXX`.

Anyway, it isn't clear how can I make a virtual folder which shown all messages from all folders on the IMAP server which has specified flag?

**Comment by ikazuhiro** [comment]
Wanderlust doesn't provide a special method to do that.  Use multi folder or `All Mail` folder if you use Gmail.
