### ISSUE TITLE
Mix multi folder and filter leads to showing wrong messages

### ISSUE THREAD

**Issue by catap** [wanderlust/wanderlust#222]
I have a few virtual folders on my IMAP server and one of them `virtual.Flagged`  is defined as:
```
*
-Trash
-Trash/*
-Junk
-Junk/*
  flagged
```
that means that it collects all emails with `\Flagged` which isn't in Trash or Junk.

When I set flag to new mail, everything works fine. But when I do it for old, it starts to show *wrong* messages in summary. I mean wrong subject and from.

But if I open message, it is fine again.

**Comment by catap** [comment]
Ok, the root cause of this issue isn't Dovecot. It is mutil folder.

I do have two folders with search:
```
/flag:Invoice/%virtual.All:"kirill@korins.ky"/plain@mx.catap.net:993!
/flag:Invoice/*%virtual.All:"kirill@korins.ky"/plain@mx.catap.net:993!
```

If I go into the first one, I have the correct mail. If I go into the second one... I have wrong one.

Before attempt I've quit WL and start it again.

**Comment by catap** [comment]
And `s all-entirely` "fixed" the issue

**Comment by catap** [comment]
I've made an experiment to prove that uid of message inside folder is constantly increased.


My setup contains a virtual folder All:
```
mx1# cat /etc/dovecot/virtual/All/dovecot-virtual
*
-INBOX/Trash
-INBOX/Trash/*
-INBOX/Junk
-INBOX/Junk/*
  all
```

which includes all messages without Trash and Junk.

So, I've send to myself two messages with some UUID as subject to easy track it.

Now let make a search for test mails:
```
mx1# doveadm search -u kirill@korins.ky subject 1a99d4e3-b086-4131-8c14-2bd42d030eb8                     
11516f16f4a3a2655b0b000079e31c01 157647
11516f16f4a3a2655b0b000079e31c01 157648
f43b012bb84b8b650d40000079e31c01 5469
f43b012bb84b8b650d40000079e31c01 5470
mx1#
```
where `11516f16f4a3a2655b0b000079e31c01` is `virtual.All` and `f43b012bb84b8b650d40000079e31c01` is `INBOX`.

Now, let move 5469 to Archive:
```
mx1# doveadm search -u kirill@korins.ky subject 1a99d4e3-b086-4131-8c14-2bd42d030eb8
fb9e821c7b778b658896000079e31c01 70419
11516f16f4a3a2655b0b000079e31c01 157648
11516f16f4a3a2655b0b000079e31c01 157649
f43b012bb84b8b650d40000079e31c01 5470
mx1#
```

Good, it has brand new msgid inside `virtual.All` and new folder `f43b012bb84b8b650d40000079e31c01`, everything is good.

Now I deleted the first message:
```
mx1# doveadm search -u kirill@korins.ky subject 1a99d4e3-b086-4131-8c14-2bd42d030eb8 
11516f16f4a3a2655b0b000079e31c01 157648
f43b012bb84b8b650d40000079e31c01 5470
mx1#
```
and moved the second one into archive as well:
```
mx1# doveadm search -u kirill@korins.ky subject 1a99d4e3-b086-4131-8c14-2bd42d030eb8 
fb9e821c7b778b658896000079e31c01 70420
11516f16f4a3a2655b0b000079e31c01 157650
mx1# 
```
UID has been changed as expected.

I really feel that Dovecot is innocent here.

Any suggestion how to dig it future?

**Comment by catap** [comment]
I've tried to remove `~/.elmo`, it rebuilds everything but the issue still exists.

**Comment by ikazuhiro** [comment]
It is probably known limitation.  Wanderlust can't detect replaced messages when operated out of folder.  Though I don't know Dovecot's specs, it would be that virtual folder's message numbers were reassigned by some order (date or internal number) when you flagged old message.

**Comment by catap** [comment]
And I discover the root cause of this inconsistence.

Dovecot guarantee the message ID in virtual folder but in my case I do have two servers, both are master and replication between them.

Sometimes the same email might have *different* message ID on different servers in the virtual's folder, when id inside non-virtual folder are match.

I've simple get one message which has that behaviour:
```
mx1# doveadm fetch -u kirill@korins.ky 'uid' mailbox virtual.All header Message-ID 'macports/macports-ports/pull/22284/c1901369454@github.com'
uid: 157786
mx1# doveadm fetch -u kirill@korins.ky 'uid' mailbox INBOX header Message-ID 'macports/macports-ports/pull/22284/c1901369454@github.com'       
uid: 5561
mx1# 
```
vs
```
mx2# doveadm fetch -u kirill@korins.ky 'uid' mailbox virtual.All header Message-ID 'macports/macports-ports/pull/22284/c1901369454@github.com'
uid: 157766
mx2# doveadm fetch -u kirill@korins.ky 'uid' mailbox INBOX header Message-ID 'macports/macports-ports/pull/22284/c1901369454@github.com'      
uid: 5561
mx2# 
```
=> `157786` vs `157766`

And if I move that message into `Archive`:
```
mx1# doveadm fetch -u kirill@korins.ky 'uid' mailbox virtual.All header Message-ID 'macports/macports-ports/pull/22284/c1901369454@github.com' 
uid: 157790
mx1# doveadm fetch -u kirill@korins.ky 'uid' mailbox Archive header Message-ID 'macports/macports-ports/pull/22284/c1901369454@github.com'     
uid: 70486
mx1# 
```
vs
```
mx2# doveadm fetch -u kirill@korins.ky 'uid' mailbox virtual.All header Message-ID 'macports/macports-ports/pull/22284/c1901369454@github.com' 
uid: 157771
mx2# doveadm fetch -u kirill@korins.ky 'uid' mailbox Archive header Message-ID 'macports/macports-ports/pull/22284/c1901369454@github.com'     
uid: 70486
mx2# 
```
again, it has unmatched uid: `157790` vs `157771`.

It definitely not a bug of wanderlust.
