### ISSUE TITLE
Use "petname" of folder inside summary line

### ISSUE THREAD

**Issue by catap** [wanderlust/wanderlust#228]
When use multi folder it might be really ugly and absolutle useless:

<img width="532" alt="Screenshot 2024-01-18 at 01 05 00" src="https://github.com/wanderlust/wanderlust/assets/37775/639be1af-f39c-4bd5-91ed-75168e62f891">

**Comment by ikazuhiro** [comment]
What do you mean by 'inside summary line'?  I noticed buffer name of sticky summary seemed not to use petname, you mean it?

**Comment by catap** [comment]
Yes, you're right. I mean that sticky summary doens't use pet name of folder and put the whole folder name. Can it be avoided somehow?

**Comment by catap** [comment]
Thus, maybe it is wise to use pet name inside message, to avoid `Loading msgdb for [very long string]`.

**Comment by ikazuhiro** [comment]
Should be done at https://github.com/wanderlust/wanderlust/commit/8ea81cd44fe68bf921d831bf0829912bd6b86db5 for buffer name.  Changing message is a hard way because the message is ouput by elmo, which can't access folder's petname.

**Comment by catap** [comment]
Confirmed, thanks!
