### ISSUE TITLE
`wl-draft-config-alist` for forwarding mail?

### ISSUE THREAD

**Issue by catap** [wanderlust/wanderlust#232]
Folks,

I'm using multi folder which is `wl-draft-parent-folder`. So, I've stuck with `reply` and headers inside `wl-draft-config-alist`.

It works quite well with one expection: forwarding.

How can I match forwarded mail headers?

**Comment by ikazuhiro** [comment]
Do you mean you want to use `forward` key like `reply`?
Wanderlust doesn't provide the feature.  Please try the below patch.

https://gist.github.com/ikazuhiro/3b82a86b8d7f7974ea8faed9580b2ea6

**Comment by catap** [comment]
Thanks for the patch. It doesn't apply clearly on c15e8ece4f34f10479e17cda19d10b98f6be3ec1 with error:
```
Patching file wl/wl-draft.el using Plan A...
Hunk #1 succeeded at 74.
Hunk #2 succeeded at 122.
patch: **** malformed patch at line 34: @@ -2321,7 +2330,5 @@ Automatically applied in draft sending time."
```
any way, if I split it into two parts: the first 3 hunks, and the last one without line 35 it works.

But this is that I'm looking for.

Thanks!

**Comment by catap** [comment]
@ikazuhiro thanks for commit, close the issue.
