### ISSUE TITLE
Email collision

### ISSUE THREAD

**Issue by catap** [wanderlust/wanderlust#236]
Folks,

I just discovered a case of email collision. My scaner sent quite trivial emails with format similar to:
```
From: some@email
To: my@email
Subject: Scanned documents
MIME-Version: 1.0
Content-Type: multipart/mixed; boundary="__MIME_Section_Boundary__"

This is a multi-part messsage in MIME format.

--__MIME_Section_Boundary__
Content-Type: application/pdf; name="=?utf-8?Q?scan.pdf?="
Content-Description: =?utf-8?Q?scan.pdf?=
Content-Disposition: attachment; filename="=?utf-8?Q?scan.pdf?="
Content-Transfer-Encoding: base64

JVBERi0xLjQKMSAwIG9iago8PCAvVHlwZSAvQ2F0YWxvZwovUGFnZXMgMiAwIFIKPj4KZW5kb2Jq
CjMgMCBvYmoKPDwgL1R5cGUgL1BhZ2UKL1BhcmVudCAyIDAgUgovUmVzb3VyY2VzIDQgMCBSCi9N
....
dHhyZWYKNDQ5ODU5OAolJUVPRg==

--__MIME_Section_Boundary__--

```

As you may see it hasn't got anything unique except an attached file, and inside msgid it creates a record like:
```
(10568 . "<76dd188b55ab031e422eeb54db3e6efesome@email>")
```
which aren't unique due to constant input fields.

So, the question: shall we add IMAP's message id into that hash to avoid such collision?

**Comment by catap** [comment]
Thus, right now code looks like:
```elisp
(defun elmo-msgdb-get-message-id-from-header ()
  (or (elmo-get-message-id-from-header 'msgdb)
      ;; no message-id, so put dummy msgid.
      (concat "<"
	      (let ((string (elmo-unfold-fetch-field "date")))
		(or (when string
		      (ignore-errors
			(timezone-make-date-sortable string)))
		    (md5 (string-as-unibyte (buffer-string)))))
	      (nth 1 (eword-extract-address-components
		      (or (std11-fetch-field "from") "nobody"))) ">")))
```
and here I not sure how `buffer-string` may return the payload which is different when email hasn't been downloaded.

**Comment by catap** [comment]
On Thu, 18 Apr 2024 17:02:54 +0200,
Kazuhiro Ito wrote:
> 
> What is actual your problem caused by duplicated message-id?
> 

I have access from WL to only the first email.

If I have scanned multiple documents, I can read only first one.

-- 
wbr, Kirill

**Comment by ikazuhiro** [comment]
Type `C-u  .` on Summary buffer or disable cache (adjust `elmo-pop3-use-cache` or `elmo-imap4-use-cache`)

> So, the question: shall we add IMAP's message id into that hash to avoid such collision?

It generally doesn't resolve the whole issue.  The same message-id  may be generated if new scanner's message is assigned the same message number with removed old messages.

FYI, Date: field is defined as required field in RFC 2822, 5322.  So your scanner's message is invalid.

**Comment by catap** [comment]
On Thu, 18 Apr 2024 17:46:53 +0200,
Kazuhiro Ito wrote:
> 
> Type `C-u  .` on Summary buffer or disable cache (adjust
> `elmo-pop3-use-cache` or `elmo-imap4-use-cache`)

Thanks, it helps!

> FYI, Date: field is defined as required field in RFC 2822, 5322.  So your scanner's message is invalid.

Well, I think this is expected.

Anyway, I found a hack: my mail server should enforces MessageId and Date to
make email valid, but due to bug iniside it, it didn't do it.

-- 
wbr, Kirill

**Comment by catap** [comment]
Close issue as defently irrelevant.

RFC 6409 requires that SMTP server should add Message-Id and Date field when mail is sent via submission port (587).
