### ISSUE TITLE
Search via flag on multiple folders leads to incorrect messages

### ISSUE THREAD

**Issue by catap** [wanderlust/wanderlust#238]
I do have a few search via flags on multiple folders wichi I define as (I keep things short, it contains 10 imap servers) :
```
/flag:Blockedbythem/*%virtual.Archive:"kirill@korins.ky"/clear@mx.catap.net:143!!,%virtual.Archive[...].com:993! "Blocked by Them"
```

When I go inside I see some unexpected emails in summary with relevant content in message buffer when I open it. But if I open it as `C-u .` I see the right one, which defently should have that flag.

Usually I add flag inside Inbox (which is also multifolder), and move it into `virtual.Archive` or `Archive` which is the same.

I not sure how to debug it future, @ikazuhiro may I ask your help?

**Comment by catap** [comment]
Well, the wrong email is stored as `~/.elmo/flag/blockedbythem/303`. After I've removed that file, nothing had changed.

**Comment by ikazuhiro** [comment]
1. Is it a different issue with #222?
2. When you add flag inside Inbox, does Summary buffer show correct message, but flag folder (`'flag/Blockedbythem`) store wrong message?

**Comment by catap** [comment]
@ikazuhiro thanks for refresh my mind about #222 ; I've double checked, and it is, indeed, the same issue with dovecot.
