### ISSUE TITLE
WL docs

### ISSUE THREAD

**Issue by egh** [wanderlust/wanderlust#82]
Hi,

I have put together a github pages repo for hosting the HTML builds of the WL info docs. The repo is here: https://github.com/egh/wl-docs and the hosted version is here: http://egh.github.io/wl-docs/

It would be great to get this moved into a wanderlust/wanderlust.github.io repo so that github.io/wanderlust could be used to host this documentation, since the only online copy of the info docs is over 10 years old now.

**Comment by egh** [comment]
@dmj @ikazuhiro Any interest in this?

**Comment by impaktor** [comment]
:+1:

**Comment by ikazuhiro** [comment]
Sorry for late response.  I will make a repository for online documents and assign write access to @egh in a few days if no objection.  @dmj, any ideas?

**Comment by egh** [comment]
Thanks!

**Comment by egh** [comment]
Thanks, @ikazuhiro . Available here: http://wanderlust.github.io/wl-docs/

It might be nice to rename the repo docs so that the URL is a little cleaner (http://wanderlust.github.io/docs/), but it's great to have the documentation available online. Thanks again!

**Comment by dmj** [comment]
Thanks and sorry for the late reply.
