### ISSUE TITLE
how to connect to pop3 server

### ISSUE THREAD

**Issue by csfreebird** [wanderlust/wanderlust#87]
I configured .wl like this, but when I run M-x wl to launch wl, it does not connect to my pop3 server. why?
Where can I find a doc for this?

;;; [[ Server Setting ]]

;; Default IMAP4 server
;;(setq elmo-imap4-default-server "localhost")
;; Default POP server
(setq elmo-pop3-default-server "mail.letv.com"
      elmo-pop3-default-user "chenshu"
      elmo-pop3-default-port '110
      elmo-pop3-default-authenticate-type 'starttls
      )
;; SMTP server
(setq wl-smtp-posting-server "mail.letv.com")
;; Default NNTP server
;;(setq elmo-nntp-default-server "localhost")
;; NNTP server name for posting
;;(setq wl-nntp-posting-server elmo-nntp-default-server)

;; IMAP authenticate type setting
;;(setq elmo-imap4-default-authenticate-type 'clear) ; raw
;(setq elmo-imap4-default-authenticate-type 'cram-md5) ; CRAM-MD5

;; POP-before-SMTP
;(setq wl-draft-send-mail-function 'wl-draft-send-mail-with-pop-before-smtp)

**Comment by LdBeth** [comment]
If you installed Wanderlust via melpa, you can press <kbd>C-h i</kbd> to see the manuals.
