### ISSUE TITLE
repo removed from Google search

### ISSUE THREAD

**Issue by gdi2290** [wanderlust/wanderlust#90]
https://www.chillingeffects.org/notices/10275257#infringing_url_598767479

**Comment by egh** [comment]
https://support.google.com/legal/contact/lr_counternotice?product=websearch

**Comment by egh** [comment]
Counterclaim filed.

**Comment by egh** [comment]
Seems to be fixed.

**Comment by impaktor** [comment]
I guess this is what happened: 
http://motherboard.vice.com/read/porn-companies-are-going-after-github
