### ISSUE TITLE
Summary mode documentation for E should be repeated in Draft mode

### ISSUE THREAD

**Issue by jech** [wanderlust/wanderlust#97]
A colleague just asked me how to continue editing a saved draft.  He had searched the *Draft* section of the documentation, but it never occurred to him to check the *Summary* section.

Please mention the Summary-Mode binding `E` at the beginning of the *Draft* section of the Wanderlust manual.

**Comment by ikazuhiro** [comment]
The comment on `wl-summary-reedit` was placed in a description of `wl-draft-save-and-exit` (`Key Bindings of Draft` node).  I have moved it into `Editing Message Body and Sending` node.
